name: cc
channels:
  - conda-forge
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.85=py314ha676f9e_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.0=py314h2b28147_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.2=h32b2ec7_100_cp314
  - python_abi=3.14=8_cp314
  - readline=8.3=h853b02a_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025c=h8577fbf_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - fair-esm==2.0.0
      - filelock==3.20.1
      - fsspec==2025.12.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - pillow==12.0.0
      - setuptools==80.9.0
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
      - triton==3.5.1
      - typing-extensions==4.15.0
prefix: /mnt/home/syxcao/conda/envs/cc
